xrdb -merge ~/.config/X11/.Xresources;
#xrdb -merge ~/.cache/wal/dwm.Xresources;
xrdb -merge ~/.cache/wal/dmenu.Xresources;
setxkbmap -option caps:escape_shifted_capslock;
xmodmap ~/.config/X11/xmodmap;

xautolock -exit;  # Just in case it's already running for some reason
xautolock -time 10 -locker slock &
sxhkd &
picom -b --experimental-backends &
bgs -z ~/pic/Wallpapers/wood-planks.jpg &
# xrootgif ~/pic/JungleWaterfall.gif &
unclutter &
xbanish &
oneko -dog -position +10-10 -time 100000 -speed 20 &
sleep .5 && xsetroot -xcf /usr/share/icons/Vimix-cursors/cursors/left_ptr 32 &

## PulseAudio >> I might switch to PipeWire soon
pidof -s runit &&
	pidof -s ! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

## dwm
#dwmblocks &
#exec dbus-run-session dwm;

## Frankenwm
#sleep 0.5 && succade &
#exec dbus-run-session start-fwm;

## Spectrwm
# exec dbus-run-session spectrwm;

## BSPWM
exec dbus-run-session bspwm;
