xrdb -merge ~/.config/X11/.Xresources;
xrdb -merge ~/.cache/wal/dwm.Xresources;
xrdb -merge ~/.cache/wal/dmenu.Xresources;
setxkbmap -option caps:escape_shifted_capslock;
xmodmap ~/.config/X11/xmodmap;

xautolock -exit;  # Just in case it's already running for some reason
xautolock -time 10 -locker slock &
sxhkd &
picom -b --experimental-backends &
bgs -z ~/pic/Wallpapers/hl-gordon-freeman-labcoat.jpg &
# xrootgif ~/pic/JungleWaterfall.gif &
unclutter &
xbanish &
oneko -dog -position +10-10 -time 100000 -speed 20 &
xsetroot -xcf /usr/share/icons/Vimix-cursors/cursors/left_ptr 32 &

## PulseAudio
pidof -s runit &&
	pidof -s ! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

## PipeWire
#/usr/bin/pipewire &
#/usr/bin/pipewire-pulse &
#/usr/bin/pipewire-media-session &

#dwmblocks &
#exec dbus-run-session dwm;
#sleep 0.5 && succade &
#exec dbus-run-session start-fwm;
exec dbus-run-session spectrwm;
